---
- name: Update and upgrade brew package repository
  homebrew:
    update_homebrew: true
    upgrade_all: true

- name: Install required packages
  homebrew:
    name:
      - gcc
      - htop
      - fzf
      - neovim
      - tmux
      - autojump
      - awscli
      - node
    state: latest

- name: Package related settings
  shell: |
    echo | /home/linuxbrew/.linuxbrew/opt/fzf/install
    git clone https://github.com/SarthakNarayan/neovim-config $HOME/.config/nvim
    echo "[ -f /home/linuxbrew/.linuxbrew/etc/profile.d/autojump.sh ] && . /home/linuxbrew/.linuxbrew/etc/profile.d/autojump.sh" >> $HOME/.zshrc

# Install apt packages
- name: Install apt packages
  become: true
  apt:
    name:
      - python3-pip
    state: latest

- name: Apt package related settings
  shell: |
    echo 'export PATH="$HOME/.local/bin:$PATH"' >> $HOME/.zshrc

- name: Install black
  pip:
    name: black
