---
- name: Get current user
  shell: echo $USER
  register: user

- name: Install zsh
  become: true
  apt:
    name:
      - zsh
    state: latest

- name: Copy sample zshrc if not present
  copy:
    src: zshrc
    dest: $HOME/.zshrc
    mode: "0644"
    force: no

- name: Set zsh as the default shell
  become: true
  shell: chsh -s /bin/zsh "{{ user.stdout }}"

- name: Reset SSH connection
  meta: reset_connection

# Install ohmyzsh
- name: Download ohmyzsh installation script
  get_url:
    url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/install.sh

- name: Make ohmyzsh installation script executable
  file:
    dest: /tmp/install.sh
    mode: a+x

- name: Run ohmyzsh installation script
  shell: echo | /tmp/install.sh

- name: Clone auto-complete plugin
  shell: git clone https://github.com/zsh-users/zsh-autosuggestions.git $HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions

- name: Clone syntax highlighting plugin
  shell: git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

- name: Add plugins to zshrc
  lineinfile:
    path: $HOME/.zshrc
    regexp: "^plugins="
    line: plugins=(git zsh-autosuggestions zsh-syntax-highlighting)

- name: Reset SSH connection
  meta: reset_connection
